=== AndresZbr/SEW/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.uniovi.es"
    xmlns="http://www.uniovi.es"
    elementFormDefault="qualified">

    <xs:element name="circuito">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="longitud" />
                <xs:element ref="anchura" />
                <xs:element ref="fecha" />
                <xs:element ref="hora" />
                <xs:element ref="vueltas" />
                <xs:element ref="localidad" />
                <xs:element ref="pais" />
                <xs:element ref="patrocinador" />
                <xs:element ref="referencias" />
                <xs:element ref="galeriaFotos" />
                <xs:element ref="galeriaVideos" />
                <xs:element ref="puntoOrigen" />
                <xs:element ref="tramos" />
                <xs:element ref="vencedor" />
                <xs:element ref="clasificacion" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="nombre" type="xs:string" />

    <xs:element name="longitud">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger"/>
        </xs:simpleType>
    </xs:element>

    <xs:element name="anchura">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:minInclusive value="10"/>
                <xs:maxInclusive value="100"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="fecha" type="xs:date" />
    <xs:element name="hora" type="xs:time" />

    <xs:element name="vueltas">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="40"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="localidad" type="xs:string" />
    <xs:element name="pais" type="xs:string" />
    <xs:element name="patrocinador" type="xs:string" />

    <xs:element name="referencias">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="referencia" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="referencia" type="xs:string" />

    <xs:element name="galeriaFotos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="foto" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="foto" type="xs:string" />

    <xs:element name="galeriaVideos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="video" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="video" type="xs:string" />

    <xs:element name="puntoOrigen">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="latitudC" />
                <xs:element ref="longitudC" />
                <xs:element ref="altitudC" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="latitudC">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="30"/>
                <xs:maxInclusive value="60"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="longitudC">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="-20"/>
                <xs:maxInclusive value="30"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="altitudC">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="-100"/>
                <xs:maxInclusive value="500"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="tramos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="tramo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="distancia" />
                <xs:element ref="longitudC" />
                <xs:element ref="latitudC" />
                <xs:element ref="altitudC" />
                <xs:element ref="sector" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="distancia">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="0.1"/>
                <xs:maxInclusive value="1000.0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="sector" type="xs:string" />

    <xs:element name="vencedor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="tiempo" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="tiempo" type="xs:duration" />

    <xs:element name="clasificacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="piloto" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="piloto" type="xs:string" />
</xs:schema>

=== AndresZbr/SEW/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
  xmlns="http://www.uniovi.es">

  <nombre>MotorLand Aragón</nombre>
  <longitud>4655</longitud>
  <anchura>15</anchura>
  <fecha>2025-09-21</fecha>
  <hora>14:00:00</hora>
  <vueltas>23</vueltas>
  <localidad>Alcañiz</localidad>
  <pais>España</pais>
  <patrocinador>GoPro</patrocinador>

  <referencias>
    <referencia>https://es.wikipedia.org/wiki/MotorLand_Aragón</referencia>
    <referencia>
      https://www.motogp.com/en/calendar/2025/event/spain/4e4f2356-d5de-43c8-ac94-39af7e7077f9?tab=overview</referencia>
    <referencia>https://www.motorlandaragon.com/es</referencia>
  </referencias>

  <galeriaFotos>
    <foto>multimedia/Motorland_Aragon_1.jpg</foto>
    <foto>multimedia/Motorland_Aragon_2.jpg</foto>
  </galeriaFotos>

  <galeriaVideos>
    <video>multimedia/Best_MotoGP</video>
  </galeriaVideos>

  <puntoOrigen>
    <latitudC>41.078459</latitudC>
    <longitudC>-0.198080</longitudC>
    <altitudC>369.03</altitudC>
  </puntoOrigen>

  <tramos>
    <tramo id="1">
      <distancia>250</distancia>
      <longitudC>-0.19808</longitudC>
      <latitudC>41.078459</latitudC>
      <altitudC>369</altitudC>
      <sector>1</sector>
    </tramo>

    <tramo id="2">
      <distancia>250</distancia>
      <longitudC>-0.20026</longitudC>
      <latitudC>41.079732</latitudC>
      <altitudC>373</altitudC>
      <sector>1</sector>
    </tramo>

    <tramo id="3">
      <distancia>250</distancia>
      <longitudC>-0.2015446501350404</longitudC>
      <latitudC>41.07873005443732</latitudC>
      <altitudC>372</altitudC>
      <sector>1</sector>
    </tramo>

    <tramo id="4">
      <distancia>250</distancia>
      <longitudC>-0.2023749070620195</longitudC>
      <latitudC>41.07857363888211</latitudC>
      <altitudC>374</altitudC>
      <sector>1</sector>
    </tramo>

    <tramo id="5">
      <distancia>250</distancia>
      <longitudC>-0.2044518029549458</longitudC>
      <latitudC>41.07911348527167</latitudC>
      <altitudC>380</altitudC>
      <sector>1</sector>
    </tramo>

    <tramo id="6">
      <distancia>250</distancia>
      <longitudC>-0.2049455186519311</longitudC>
      <latitudC>41.07950507818167</latitudC>
      <altitudC>383</altitudC>
      <sector>1</sector>
    </tramo>

    <tramo id="7">
      <distancia>250</distancia>
      <longitudC>-0.2054436891324085</longitudC>
      <latitudC>41.08172855391199</latitudC>
      <altitudC>397</altitudC>
      <sector>1</sector>
    </tramo>

    <tramo id="8">
      <distancia>250</distancia>
      <longitudC>-0.2061016711802255</longitudC>
      <latitudC>41.08223242645494</latitudC>
      <altitudC>396</altitudC>
      <sector>2</sector>
    </tramo>

    <tramo id="9">
      <distancia>250</distancia>
      <longitudC>-0.2067831033607082</longitudC>
      <latitudC>41.08257472740372</latitudC>
      <altitudC>392</altitudC>
      <sector>2</sector>
    </tramo>

    <tramo id="10">
      <distancia>250</distancia>
      <longitudC>-0.2071817535729492</longitudC>
      <latitudC>41.08248644510297</latitudC>
      <altitudC>396</altitudC>
      <sector>2</sector>
    </tramo>

    <tramo id="11">
      <distancia>250</distancia>
      <longitudC>-0.207649</longitudC>
      <latitudC>41.081133</latitudC>
      <altitudC>405</altitudC>
      <sector>2</sector>
    </tramo>

    <tramo id="12">
      <distancia>250</distancia>
      <longitudC>-0.2086693136369278</longitudC>
      <latitudC>41.08029867416398</latitudC>
      <altitudC>406</altitudC>
      <sector>2</sector>
    </tramo>

    <tramo id="13">
      <distancia>250</distancia>
      <longitudC>-0.2093537950480384</longitudC>
      <latitudC>41.08000300778949</latitudC>
      <altitudC>407</altitudC>
      <sector>2</sector>
    </tramo>

    <tramo id="14">
      <distancia>250</distancia>
      <longitudC>-0.209912</longitudC>
      <latitudC>41.080049</latitudC>
      <altitudC>407</altitudC>
      <sector>2</sector>
    </tramo>

    <tramo id="15">
      <distancia>250</distancia>
      <longitudC>-0.2101668599539108</longitudC>
      <latitudC>41.08028878511966</latitudC>
      <altitudC>407</altitudC>
      <sector>2</sector>
    </tramo>

    <tramo id="16">
      <distancia>250</distancia>
      <longitudC>-0.2107051979808172</longitudC>
      <latitudC>41.08300575286325</latitudC>
      <altitudC>399</altitudC>
      <sector>2</sector>
    </tramo>

    <tramo id="17">
      <distancia>250</distancia>
      <longitudC>-0.2104026461377484</longitudC>
      <latitudC>41.08328098751693</latitudC>
      <altitudC>396</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="18">
      <distancia>250</distancia>
      <longitudC>-0.210045579954018</longitudC>
      <latitudC>41.08336411769223</latitudC>
      <altitudC>395</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="19">
      <distancia>250</distancia>
      <longitudC>-0.2097606449032741</longitudC>
      <latitudC>41.0835635614125</latitudC>
      <altitudC>391</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="20">
      <distancia>250</distancia>
      <longitudC>-0.2100514926915875</longitudC>
      <latitudC>41.0838906262252</latitudC>
      <altitudC>387</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="21">
      <distancia>250</distancia>
      <longitudC>-0.2107887505047967</longitudC>
      <latitudC>41.08417615028305</latitudC>
      <altitudC>385</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="22">
      <distancia>250</distancia>
      <longitudC>-0.2114517108922143</longitudC>
      <latitudC>41.08423760614389</latitudC>
      <altitudC>384</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="23">
      <distancia>250</distancia>
      <longitudC>-0.212059</longitudC>
      <latitudC>41.084167</latitudC>
      <altitudC>383</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="24">
      <distancia>250</distancia>
      <longitudC>-0.2124900110125161</longitudC>
      <latitudC>41.08395542164639</latitudC>
      <altitudC>384</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="25">
      <distancia>250</distancia>
      <longitudC>-0.212786466765742</longitudC>
      <latitudC>41.08358802569978</latitudC>
      <altitudC>386</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="26">
      <distancia>250</distancia>
      <longitudC>-0.2128564903561181</longitudC>
      <latitudC>41.0831566673436</latitudC>
      <altitudC>388</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="27">
      <distancia>250</distancia>
      <longitudC>-0.2126310301775214</longitudC>
      <latitudC>41.08165647708953</latitudC>
      <altitudC>390</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="28">
      <distancia>250</distancia>
      <longitudC>-0.212459</longitudC>
      <latitudC>41.081116</latitudC>
      <altitudC>391</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="29">
      <distancia>250</distancia>
      <longitudC>-0.2115271017841835</longitudC>
      <latitudC>41.07967811183462</latitudC>
      <altitudC>397</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="30">
      <distancia>250</distancia>
      <longitudC>-0.210549</longitudC>
      <latitudC>41.078891</latitudC>
      <altitudC>392</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="31">
      <distancia>250</distancia>
      <longitudC>-0.2089334654241815</longitudC>
      <latitudC>41.07939091223915</latitudC>
      <altitudC>399</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="32">
      <distancia>250</distancia>
      <longitudC>-0.2082039464048879</longitudC>
      <latitudC>41.07935280391707</latitudC>
      <altitudC>393</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="33">
      <distancia>250</distancia>
      <longitudC>-0.206492</longitudC>
      <latitudC>41.078244</latitudC>
      <altitudC>381</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="34">
      <distancia>250</distancia>
      <longitudC>-0.206812</longitudC>
      <latitudC>41.077375</latitudC>
      <altitudC>378</altitudC>
      <sector>3</sector>
    </tramo>

    <tramo id="35">
      <distancia>250</distancia>
      <longitudC>-0.1954385866271846</longitudC>
      <latitudC>41.07427792694129</latitudC>
      <altitudC>356</altitudC>
      <sector>4</sector>
    </tramo>

    <tramo id="36">
      <distancia>250</distancia>
      <longitudC>-0.194563162504352</longitudC>
      <latitudC>41.07448622205776</latitudC>
      <altitudC>360</altitudC>
      <sector>4</sector>
    </tramo>

    <tramo id="37">
      <distancia>250</distancia>
      <longitudC>-0.1939671942187804</longitudC>
      <latitudC>41.07504498851593</latitudC>
      <altitudC>364</altitudC>
      <sector>4</sector>
    </tramo>

    <tramo id="38">
      <distancia>250</distancia>
      <longitudC>-0.194153</longitudC>
      <latitudC>41.075969</latitudC>
      <altitudC>365</altitudC>
      <sector>4</sector>
    </tramo>

    <tramo id="39">
      <distancia>250</distancia>
      <longitudC>-0.19808</longitudC>
      <latitudC>41.078459</latitudC>
      <altitudC>369</altitudC>
      <sector>4</sector>
    </tramo>
  </tramos>

  <vencedor>
    <nombre>Marc Márquez</nombre>
    <tiempo>PT42M15S</tiempo>
  </vencedor>

  <clasificacion>
    <piloto>Marc Márquez</piloto>
    <piloto>Alex Márquez</piloto>
    <piloto>Fracesco Bagnaia</piloto>
  </clasificacion>

</circuito>
